### ISSUE TITLE
Won't work on OneDrive

### ISSUE THREAD

**Issue by subtra3t** [IAmMaulik/KeyloggerPy#2]
Any operating system that has OneDrive integrated won't be able to use this.

**Comment by IAmMaulik** [comment]
Why will it not work?

**Comment by subtra3t** [comment]
> Why will it not work?

Because windows will store the desktop directory differently. For example, the following desktop directory:

```
C:/users/user/desktop/
```

would change to the following:

```
C:/users/user/OneDrive/desktop/
```

**Comment by IAmMaulik** [comment]
Oh, I see.
Do you know of any possible fixes of this

**Comment by subtra3t** [comment]
> Oh, I see.
> Do you know of any possible fixes of this

Unfortunately, there is no way to know if OneDrive is installed on a PC. But you *could* make it so that the user inputs a folder of their own choice.

**Comment by IAmMaulik** [comment]
So is the start-up directory also stored differently?
```
C:/Users/user/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Startup/main.pyw
```
It is it the same

**Comment by subtra3t** [comment]
> So is the start-up directory also stored differently?
> 
> ```
> C:/Users/user/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Startup/main.pyw
> ```
> 
> It is it the same

I don't think so. OneDrive is not supposed to mess up with app data, since there's some stuff there that might potentially be privacy-infringing.

**Comment by IAmMaulik** [comment]
Ok then, that was an easy fix.
Thanks for pointing that out to me
